core/urls.py
from django.urls import path

app_name = "core"

from core.views import metods, auth_check, test_metod

urlpatterns = [
    path("", metods, name="metods_list"),
    path("metods/auth_check/", auth_check, name="auth_check"),
    path("metods/test_metod/", test_metod, name="test_metod"),
]

translator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms


class TestForm(forms.Form):
    text_param = forms.CharField(label="Текстовый параметр", max_length=10)
    numeric_param = forms.IntegerField(label="Числовой параметр", max_value=5)

core/views.py
from django.shortcuts import render
from core.forms import TestForm
from translator.service import ClientRpc, ClientRpcError, ClientRpcHttpError

# Create your views here.
def metods(request):
    return render(request, "metods.html")


def auth_check(request):
    try:
        rpc_client = ClientRpc()
        res = rpc_client.get(method="auth.check")
        rpc_client.close()
    except ClientRpcError as e:
        context = {"error": {"code": e.code, "message": e.message, "data": e.data}}
    except ClientRpcHttpError as e:
        context = {"error": {"status": e.status, "reason": e.reason}}
    else:
        context = {"data": res}
    return render(request, "result.html", context)


def test_metod(request):
    if request.method == "POST":
        form = TestForm(request.POST)
        if form.is_valid():
            param1 = form.cleaned_data["text_param"]
            param2 = form.cleaned_data["numeric_param"]
            try:
                rpc_client = ClientRpc()
                res = rpc_client.get(
                    method="test.error",
                    params={
                        "param1": param1,
                        "param2": param2,
                    },
                )
                rpc_client.close()
            except ClientRpcError as e:
                context = {
                    "error": {"code": e.code, "message": e.message, "data": e.data}
                }
            except ClientRpcHttpError as e:
                context = {"error": {"status": e.status, "reason": e.reason}}
            else:
                context = {"data": res}
            print(context)
            return render(request, "result.html", context)
    else:
        form = TestForm()
    return render(request, "form.html", {"form": form})

core/templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="ru">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="description" content="Транслятор api">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Place favicon.ico in the root directory -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

    <meta name="theme-color" content="#fafafa">
</head>
<header>
    <div class="logo"> <img src="{% static 'logo/logo.png' %}" width=293 height=125 alt="logo"></div>
    <nav>
        <ul class="nav">
            {% block navbar %}
            {% endblock %}
        </ul>
    </nav>
</header>

<body>
    <main>
        <div class="main_wrapper">
            {% block content %}
            {% endblock %}
            {% block javascript %}
            {% endblock %}
        </div>
    </main>
    <aside>
    </aside>
    <footer>
        <div class="address">
            <address>
                &copy; Azat715 contact: <a href="mailto:azat715@gmail.com">Mail me</a>
            </address>
        </div>
    </footer>
    <script src="{% static 'js/vendor/modernizr-3.11.2.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

core/templates/form.html
{% extends "./base.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Запрос">
</form>
{% endblock %}

core/templates/metods.html
{% extends "./base.html" %}

{% block content %}
<h4>Список методов</h4>

<div class="w-75">
    <ul class="list-group">
        <li class="list-group-item">
            <span>Проверка аутентификации</span>
            <a class="btn btn-primary" href="{% url 'core:auth_check' %}">Запрос</a>
        </li>
        <li class="list-group-item">
            <span>Тестовый запрос(всегда возвращает ошибку)</span>
            <a class="btn btn-primary" href="{% url 'core:test_metod' %}">Запрос</a>
        </li>
    </ul>
</div>
{% endblock %}

core/templates/result.html
{% extends "./base.html" %}

{% block navbar %}
<li class="nav-item"><a href="{% url 'core:metods_list' %}">Методы</a></li>
{% endblock %}
{% block content %}
<h4>Результат запроса</h4>
{% if data %}
<pre>
{{ data | pprint }}
</pre>
{% endif %}
{% if error %}
<h5>Произошла ошибка</h5>
<span>Code: {{ error.code }}</span><br>
<span>Message: {{ error.message }}</span><br>
<span>Data: {{ error.data }}</span><br>
{% endif %}
{% endblock %}